In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
%matplotlib inline

In [4]:
iris = load_iris()
X = iris.data
y = iris.target

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size =0.3 , random_state =2018)


In [10]:
knn = KNN(n_neighbors =3)

In [11]:
knn.fit(X_train , y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [12]:
knn.predict(iris.data[:1,:])

array([0])

In [13]:
knn.predict(iris.data[:45,:])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [14]:
knn_pred = knn.predict(X_test)
knn_pred

array([0, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 0,
       2, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2,
       1])

In [15]:
print(accuracy_score(y_test, knn_pred))

0.9777777777777777


In [16]:
print(confusion_matrix(y_test, knn_pred))

[[18  0  0]
 [ 0 11  0]
 [ 0  1 15]]


In [17]:
print(classification_report(y_test, knn_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        18
          1       0.92      1.00      0.96        11
          2       1.00      0.94      0.97        16

avg / total       0.98      0.98      0.98        45

