In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
iris = datasets.load_iris()
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [3]:
X = iris.data[:,[2,3]]
y = iris.target


In [6]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size =0.3 ,random_state = 2018)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)


In [8]:
cls = GaussianNB()

In [10]:
cls.fit(X_train_std , y_train)

GaussianNB(priors=None)

In [11]:
print("Accuracy : ", accuracy_score(y_test , cls.predict(X_test_std)))

Accuracy :  0.9777777777777777


In [12]:
print("Confusion Matrix : ", confusion_matrix(y_test , cls.predict(X_test_std)))

Confusion Matrix :  [[18  0  0]
 [ 0 11  0]
 [ 0  1 15]]


In [13]:
print("Classification report : ", classification_report(y_test , cls.predict(X_test_std)))

Classification report :               precision    recall  f1-score   support

          0       1.00      1.00      1.00        18
          1       0.92      1.00      0.96        11
          2       1.00      0.94      0.97        16

avg / total       0.98      0.98      0.98        45

